version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: leads-postgres
    restart: always
    environment:
      POSTGRES_USER: leads_user
      POSTGRES_PASSWORD: leads_pass
      POSTGRES_DB: leads_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
